name: validate-renovate

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/validate-renovate.yaml
      - renovate.json5
  push:
    branches:
      - main
    paths:
      - .github/workflows/validate-renovate.yaml
      - renovate.json5

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rinchsan/renovate-config-validator@v0.2.0
        with:
          pattern: 'renovate.json5'

